# Generated by Django 4.2.7 on 2024-02-02 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettereventdate',
            name='year_exact',
            field=models.IntegerField(blank=True, help_text='The exact year of the value (if known). This will override the values in the lower and upper bounds fields.', null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='lettereventdate',
            name='year_lower',
            field=models.IntegerField(default=400, help_text='The earliest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='lettereventdate',
            name='year_upper',
            field=models.IntegerField(default=800, help_text='The latest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)]),
        ),
    ]
