# Generated by Django 4.2.7 on 2024-02-05 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_lettereventdate_year_exact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpistolaryEventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epistolary_event', models.ForeignKey(help_text='The epistolary event that was triggered by a world event', on_delete=django.db.models.deletion.CASCADE, to='event.epistolaryevent')),
            ],
        ),
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_lower', models.IntegerField(default=400, help_text='The earliest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('year_upper', models.IntegerField(default=800, help_text='The latest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('year_exact', models.IntegerField(blank=True, help_text='The exact year of the value (if known). This will override the values in the lower and upper bounds fields.', null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('name', models.CharField(help_text="The name of the event, e.g. 'The Great Fire of London' or 'The Battle of Hastings'.", max_length=256)),
                ('note', models.TextField(blank=True, help_text='Additional notes that describe the event and its relevance to the letters.')),
                ('epistolary_events', models.ManyToManyField(related_name='triggers', through='event.EpistolaryEventTrigger', to='event.epistolaryevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='epistolaryeventtrigger',
            name='world_event',
            field=models.ForeignKey(help_text='The world event that triggered an epistolary event', on_delete=django.db.models.deletion.CASCADE, to='event.worldevent'),
        ),
    ]
