# Generated by Django 4.2.7 on 2024-02-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_letteraction_gifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldevent',
            name='epistolary_events',
        ),
        migrations.AddField(
            model_name='epistolaryevent',
            name='triggered_world_events',
            field=models.ManyToManyField(help_text='World events triggered by this epistolary event', related_name='world_event_triggers', through='event.EpistolaryEventTrigger', to='event.worldevent'),
        ),
        migrations.AddField(
            model_name='epistolaryeventtrigger',
            name='certainty',
            field=models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?'),
        ),
        migrations.AddField(
            model_name='epistolaryeventtrigger',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='epistolaryeventtrigger',
            name='epistolary_event',
            field=models.ForeignKey(help_text='The epistolary event that triggered a world event', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_by_epistolary_events', to='event.epistolaryevent'),
        ),
        migrations.AlterField(
            model_name='epistolaryeventtrigger',
            name='world_event',
            field=models.ForeignKey(help_text='The world event that was triggered by an epistolary event', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_for_world_events', to='event.worldevent'),
        ),
        migrations.CreateModel(
            name='WorldEventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('epistolary_event', models.ForeignKey(help_text='The epistolary event that was triggered by a world event', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_by_world_events', to='event.epistolaryevent')),
                ('world_event', models.ForeignKey(help_text='The world event that triggered an epistolary event', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_for_epistolary_events', to='event.worldevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldEventSelfTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('triggered_world_event', models.ForeignKey(help_text='The world event that was triggered by another world event', on_delete=django.db.models.deletion.CASCADE, related_name='self_triggers_for_world_events', to='event.worldevent')),
                ('triggering_world_event', models.ForeignKey(help_text='The world event that triggered another world event', on_delete=django.db.models.deletion.CASCADE, related_name='self_triggered_by_world_events', to='event.worldevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpistolaryEventSelfTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('triggered_epistolary_event', models.ForeignKey(help_text='The epistolary event that was triggered by another epistolary event', on_delete=django.db.models.deletion.CASCADE, related_name='self_triggers_for_epistolary_events', to='event.epistolaryevent')),
                ('triggering_epistolary_event', models.ForeignKey(help_text='The epistolary event that triggered another epistolary event', on_delete=django.db.models.deletion.CASCADE, related_name='self_triggered_by_epistolary_events', to='event.epistolaryevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='epistolaryevent',
            name='triggered_epistolary_events',
            field=models.ManyToManyField(help_text='Other epistolary events triggered by this epistolary event', through='event.EpistolaryEventSelfTrigger', to='event.epistolaryevent'),
        ),
        migrations.AddField(
            model_name='worldevent',
            name='triggered_epistolary_events',
            field=models.ManyToManyField(help_text='Epistolary events triggered by this world event', related_name='epistolary_event_triggers', through='event.WorldEventTrigger', to='event.epistolaryevent'),
        ),
        migrations.AddField(
            model_name='worldevent',
            name='triggered_world_events',
            field=models.ManyToManyField(help_text='Other world events triggered by this world event', through='event.WorldEventSelfTrigger', to='event.worldevent'),
        ),
    ]
