# Generated by Django 4.2.7 on 2024-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_gift'),
        ('event', '0006_remove_worldevent_epistolary_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteraction',
            name='gifts',
            field=models.ManyToManyField(blank=True, help_text='Gifts associated to this letter action', related_name='letter_actions', to='letter.gift'),
        ),
    ]
