# Generated by Django 4.2.7 on 2024-02-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
        ("event", "0008_rename_person_role_agent_alter_role_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='letteraction',
            name='space_descriptions',
            field=models.ManyToManyField(blank=True, help_text='Descriptions of the space in which this action took place', to='space.spacedescription'),
        ),
    ]
