# Generated by Django 4.2.7 on 2024-03-27 10:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0011_alter_agent_gender_alter_agent_is_group_and_more"),
        ("event", "0009_letteraction_space_descriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterActionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="events", through="event.Role", to="person.agent"
                    ),
                ),
                (
                    "epistolary_events",
                    models.ManyToManyField(
                        help_text="epistolary events this letter action belongs to",
                        related_name="letter_actions",
                        to="event.epistolaryevent",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="epistolary_events",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="gifts",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="id",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="letters",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="space_descriptions",
        ),
        migrations.CreateModel(
            name="LetterActionDescription",
            fields=[
                (
                    "letteractionbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.letteractionbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("event.letteractionbase", models.Model),
        ),
    ]
