# Generated by Django 4.2.7 on 2024-04-08 12:22

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('event', '0009_letteraction_space_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='a name to help identify this object', max_length=128)),
                ('description', models.TextField(blank=True, help_text='longer description to help identify this object')),
                ('location', models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200)),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is the entity presented in the text?', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('year_lower', models.IntegerField(default=400, help_text='The earliest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('year_upper', models.IntegerField(default=800, help_text='The latest possible year for this value', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('year_exact', models.IntegerField(blank=True, help_text='The exact year of the value (if known). This will override the values in the lower and upper bounds fields.', null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.spacedescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='epistolaryeventselftrigger',
            name='triggered_epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventselftrigger',
            name='triggering_epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventtrigger',
            name='epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventtrigger',
            name='world_event',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='epistolary_events',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='gifts',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='letters',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='space_descriptions',
        ),
        migrations.RemoveField(
            model_name='letteractioncategory',
            name='letter_action',
        ),
        migrations.RemoveField(
            model_name='lettereventdate',
            name='letter_action',
        ),
        migrations.RemoveField(
            model_name='role',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='role',
            name='letter_action',
        ),
        migrations.RemoveField(
            model_name='worldevent',
            name='triggered_epistolary_events',
        ),
        migrations.RemoveField(
            model_name='worldevent',
            name='triggered_world_events',
        ),
        migrations.RemoveField(
            model_name='worldeventselftrigger',
            name='triggered_world_event',
        ),
        migrations.RemoveField(
            model_name='worldeventselftrigger',
            name='triggering_world_event',
        ),
        migrations.RemoveField(
            model_name='worldeventtrigger',
            name='epistolary_event',
        ),
        migrations.RemoveField(
            model_name='worldeventtrigger',
            name='world_event',
        ),
        migrations.DeleteModel(
            name='EpistolaryEvent',
        ),
        migrations.DeleteModel(
            name='EpistolaryEventSelfTrigger',
        ),
        migrations.DeleteModel(
            name='EpistolaryEventTrigger',
        ),
        migrations.DeleteModel(
            name='LetterAction',
        ),
        migrations.DeleteModel(
            name='LetterActionCategory',
        ),
        migrations.DeleteModel(
            name='LetterEventDate',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='WorldEvent',
        ),
        migrations.DeleteModel(
            name='WorldEventSelfTrigger',
        ),
        migrations.DeleteModel(
            name='WorldEventTrigger',
        ),
    ]
