# Generated by Django 4.2.7 on 2024-03-27 20:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0012_agentbase_remove_agent_gender_group_constraint_and_more"),
        ("letter", "0009_giftbase_letterbase_remove_gift_description_and_more"),
        ("source", "0004_delete_reference"),
        ("space", "0002_spacedescriptionbase_and_more"),
        ("event", "0009_letteraction_space_descriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letteraction",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="epistolary_events",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="gifts",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="id",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="letters",
        ),
        migrations.RemoveField(
            model_name="letteraction",
            name="space_descriptions",
        ),
        migrations.AlterField(
            model_name="role",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="person.agentbase"
            ),
        ),
        migrations.CreateModel(
            name="LetterActionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="events",
                        through="event.Role",
                        to="person.agentbase",
                    ),
                ),
                (
                    "epistolary_events",
                    models.ManyToManyField(
                        help_text="epistolary events this letter action belongs to",
                        related_name="letter_actions",
                        to="event.epistolaryevent",
                    ),
                ),
                (
                    "gifts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Gifts associated to this letter action",
                        related_name="letter_actions",
                        to="letter.giftbase",
                    ),
                ),
                (
                    "letters",
                    models.ManyToManyField(
                        help_text="letters involved in this event",
                        related_name="events",
                        to="letter.letterbase",
                    ),
                ),
                (
                    "space_descriptions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Descriptions of the space in which this action took place",
                        to="space.spacedescriptionbase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="letteraction",
            name="letteractionbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="event.letteractionbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="letteractioncategory",
            name="letter_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="event.letteractionbase",
            ),
        ),
        migrations.AlterField(
            model_name="lettereventdate",
            name="letter_action",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date",
                to="event.letteractionbase",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="letter_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.letteractionbase"
            ),
        ),
        migrations.CreateModel(
            name="LetterActionDescription",
            fields=[
                (
                    "letteractionbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.letteractionbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="event.letteraction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("event.letteractionbase", models.Model),
        ),
    ]
