# Generated by Django 4.2.7 on 2024-04-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_letteraction_space_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letteraction',
            name='actors',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
