# Generated by Django 4.2.7 on 2024-04-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_letteraction_actors_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letteraction',
            name='gifts',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='letters',
        ),
    ]
