# Generated by Django 4.2.7 on 2024-04-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_giftaddressee_giftdescription_giftmaterial_and_more'),
        ('event', '0010_eventdescription_eventdescriptionagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdescriptionletter',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription'),
        ),
        migrations.AddField(
            model_name='eventdescriptiongift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription'),
        ),
        migrations.AddField(
            model_name='eventdescriptiongift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription'),
        ),
        migrations.AddField(
            model_name='eventdescriptiondate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='event.eventdescription'),
        ),
    ]
