# Generated by Django 4.2.7 on 2024-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_letteractionbase_remove_letteraction_actors_and_more"),
        ("letter", "0009_giftbase_letterbase_remove_gift_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letteractionbase",
            name="gifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gifts associated to this letter action",
                related_name="letter_actions",
                to="letter.giftbase",
            ),
        ),
        migrations.AddField(
            model_name="letteractionbase",
            name="letters",
            field=models.ManyToManyField(
                help_text="letters involved in this event",
                related_name="events",
                to="letter.letterbase",
            ),
        ),
    ]
