# Generated by Django 4.2.7 on 2024-04-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_letteraction_gifts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epistolaryeventselftrigger',
            name='triggered_epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventselftrigger',
            name='triggering_epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventtrigger',
            name='epistolary_event',
        ),
        migrations.RemoveField(
            model_name='epistolaryeventtrigger',
            name='world_event',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='epistolary_events',
        ),
        migrations.RemoveField(
            model_name='letteraction',
            name='space_descriptions',
        ),
        migrations.RemoveField(
            model_name='letteractioncategory',
            name='letter_action',
        ),
        migrations.RemoveField(
            model_name='lettereventdate',
            name='letter_action',
        ),
        migrations.RemoveField(
            model_name='worldevent',
            name='triggered_epistolary_events',
        ),
        migrations.RemoveField(
            model_name='worldevent',
            name='triggered_world_events',
        ),
        migrations.RemoveField(
            model_name='worldeventselftrigger',
            name='triggered_world_event',
        ),
        migrations.RemoveField(
            model_name='worldeventselftrigger',
            name='triggering_world_event',
        ),
        migrations.RemoveField(
            model_name='worldeventtrigger',
            name='epistolary_event',
        ),
        migrations.RemoveField(
            model_name='worldeventtrigger',
            name='world_event',
        ),
        migrations.DeleteModel(
            name='EpistolaryEvent',
        ),
        migrations.DeleteModel(
            name='EpistolaryEventSelfTrigger',
        ),
        migrations.DeleteModel(
            name='EpistolaryEventTrigger',
        ),
        migrations.DeleteModel(
            name='LetterAction',
        ),
        migrations.DeleteModel(
            name='LetterActionCategory',
        ),
        migrations.DeleteModel(
            name='LetterEventDate',
        ),
        migrations.DeleteModel(
            name='WorldEvent',
        ),
        migrations.DeleteModel(
            name='WorldEventSelfTrigger',
        ),
        migrations.DeleteModel(
            name='WorldEventTrigger',
        ),
    ]
