# Generated by Django 4.2.7 on 2024-03-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_delete_reference"),
        ("space", "0003_spacedescriptionbase_and_more"),
        ("event", "0011_letteractionbase_gifts_letteractionbase_letters"),
    ]

    operations = [
        migrations.AddField(
            model_name="letteractionbase",
            name="space_descriptions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Descriptions of the space in which this action took place",
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.AddField(
            model_name="letteraction",
            name="letteractionbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="event.letteractionbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="letteractioncategory",
            name="letter_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="event.letteractionbase",
            ),
        ),
        migrations.AlterField(
            model_name="lettereventdate",
            name="letter_action",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date",
                to="event.letteractionbase",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="letter_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.letteractionbase"
            ),
        ),
        migrations.AddField(
            model_name="letteractiondescription",
            name="source",
            field=models.ForeignKey(
                help_text="The source in which this description occurs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="source.source",
            ),
        ),
        migrations.AddField(
            model_name="letteractiondescription",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_descriptions",
                to="event.letteraction",
            ),
        ),
    ]
