# Generated by Django 4.2.7 on 2024-04-11 12:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0008_alter_spacedescription_source'),
        ('source', '0005_placeholder_source'),
        ('person', '0014_alter_persondateofbirth_person_and_more'),
        ('letter', '0012_preservedletter_preservedletterrole_and_more'),
        ('event', '0012_remove_epistolaryeventselftrigger_triggered_epistolary_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this entity presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.spacedescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescriptionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='agents involved in this event', through='event.EventDescriptionAgent', to='person.agentdescription'),
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='gifts',
            field=models.ManyToManyField(blank=True, help_text='gifts involved in this event', through='event.EventDescriptionGift', to='letter.giftdescription'),
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='letters',
            field=models.ManyToManyField(blank=True, help_text='letters involved in this event', through='event.EventDescriptionLetter', to='letter.letterdescription'),
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='source',
            field=models.ForeignKey(help_text='Source text containing this description', on_delete=django.db.models.deletion.PROTECT, to='source.source'),
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='spaces',
            field=models.ManyToManyField(blank=True, help_text='locations involved in this event', through='event.EventDescriptionSpace', to='space.spacedescription'),
        ),
    ]
