# Generated by Django 4.2.7 on 2024-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventcategory_eventdescription_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'event categories'},
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('events', models.ManyToManyField(blank=True, help_text='Events that make up this episode', to='event.eventdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
