# Generated by Django 4.2.7 on 2024-04-25 10:13

from django.db import migrations, models


def migrate_source_location_to_page(apps, schema_editor):
    EventDescription = apps.get_model("event", "EventDescription")
    for event_description in EventDescription.objects.all():
        if event_description.source_location:
            event_description.page = event_description.source_location
            event_description.save()


def migrate_page_to_source_location(apps, schema_editor):
    EventDescription = apps.get_model("event", "EventDescription")
    for event_description in EventDescription.objects.all():
        if event_description.page:
            event_description.source_location = event_description.page
            event_description.save()


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_alter_eventcategory_options_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdescription",
            name="book",
            field=models.CharField(
                blank=True, help_text="The book in the source", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="eventdescription",
            name="chapter",
            field=models.CharField(
                blank=True,
                help_text="The chapter or chapters in the source",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="eventdescription",
            name="page",
            field=models.CharField(
                blank=True,
                help_text="The page number or page range in the source",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            code=migrate_source_location_to_page,
            reverse_code=migrate_page_to_source_location,
        ),
        migrations.RemoveField(
            model_name="eventdescription",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="eventdescriptionagent",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="eventdescriptiongift",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="eventdescriptionletter",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="eventdescriptionspace",
            name="source_location",
        ),
    ]
