# Generated by Django 4.2.7 on 2024-06-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_study", "0004_alter_casestudy_episodes"),
        ("event", "0017_remove_eventdescriptionagent_source_terminology_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Episode",
            new_name="Series",
        ),
    ]
