# Generated by Django 4.2.7 on 2024-06-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0018_rename_episode_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="series",
            old_name="events",
            new_name="episodes",
        ),
    ]
