# Generated by Django 4.2.7 on 2024-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0015_remove_giftdescriptionsender_agent_and_more"),
        ("space", "0016_settlement_regions"),
        ("person", "0018_alter_personreference_description_and_more"),
        ("event", "0020_rename_eventdescription_episode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventDescriptionAgent",
            new_name="EpisodeAgent",
        ),
        migrations.RenameModel(
            old_name="EventCategory",
            new_name="EpisodeCategory",
        ),
        migrations.RenameModel(
            old_name="EventDescriptionGift",
            new_name="EpisodeGift",
        ),
        migrations.RenameModel(
            old_name="EventDescriptionLetter",
            new_name="EpisodeLetter",
        ),
        migrations.RenameModel(
            old_name="EventDescriptionSpace",
            new_name="EpisodeSpace",
        ),
        migrations.AlterModelOptions(
            name="episodecategory",
            options={"verbose_name_plural": "episode categories"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "series"},
        ),
        migrations.RenameField(
            model_name="episodeagent",
            old_name="event",
            new_name="episode",
        ),
        migrations.RenameField(
            model_name="episodegift",
            old_name="event",
            new_name="episode",
        ),
        migrations.RenameField(
            model_name="episodeletter",
            old_name="event",
            new_name="episode",
        ),
        migrations.RenameField(
            model_name="episodespace",
            old_name="event",
            new_name="episode",
        ),
        migrations.AlterField(
            model_name="episode",
            name="agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="agents involved in this episode",
                through="event.EpisodeAgent",
                to="person.agentdescription",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="categories",
            field=models.ManyToManyField(
                help_text="labels assigned to this episode",
                related_name="episodes",
                to="event.episodecategory",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="gifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="gifts involved in this episode",
                through="event.EpisodeGift",
                to="letter.giftdescription",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="letters",
            field=models.ManyToManyField(
                blank=True,
                help_text="letters involved in this episode",
                through="event.EpisodeLetter",
                to="letter.letterdescription",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="spaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="locations involved in this episode",
                through="event.EpisodeSpace",
                to="space.spacedescription",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="episodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Episodes that make up this series",
                to="event.episode",
            ),
        ),
    ]
