# Generated by Django 4.2.7 on 2024-08-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0021_rename_eventdescriptionagent_episodeagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
