# Generated by Django 4.2.7 on 2024-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_episode_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeagent',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='episodegift',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='episodeletter',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='episodespace',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
    ]
