# Generated by Django 4.2.7 on 2024-09-03 13:19

from django.db import migrations
from typing import Type
from core.models import DescriptionField, SourceMention


def fill_in_blank_source_mention(Model: Type[DescriptionField]):
    Model.objects.filter(source_mention="").update(source_mention=SourceMention.DIRECT)


def fill_in_source_mention_defaults(apps, schema_editor):
    models = [
        apps.get_model("event", "EpisodeAgent"),
        apps.get_model("event", "EpisodeLetter"),
        apps.get_model("event", "EpisodeGift"),
        apps.get_model("event", "EpisodeSpace"),
        apps.get_model("person", "AgentDescriptionGender"),
        apps.get_model("person", "AgentDescriptionLocation"),
        apps.get_model("letter", "LetterDescriptionCategory"),
        apps.get_model("letter", "GiftDescriptionCategory"),
    ]

    for Model in models:
        fill_in_blank_source_mention(Model)


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0024_alter_episodeagent_source_mention_and_more"),
        ("person", "0021_alter_agentdescriptiongender_source_mention_and_more"),
        ("letter", "0019_alter_giftdescriptioncategory_source_mention_and_more"),
    ]

    operations = [
        migrations.RunPython(
            fill_in_source_mention_defaults, migrations.RunPython.noop
        ),
    ]
