# Generated by Django 4.2.7 on 2024-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0019_alter_giftdescriptioncategory_source_mention_and_more'),
        ('space', '0018_alter_regionfield_source_mention_and_more'),
        ('person', '0021_alter_agentdescriptiongender_source_mention_and_more'),
        ('event', '0025_fill_in_blank_sourcemention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='agents involved in this episode', related_name='episodes', through='event.EpisodeAgent', to='person.agentdescription'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='gifts',
            field=models.ManyToManyField(blank=True, help_text='gifts involved in this episode', related_name='episodes', through='event.EpisodeGift', to='letter.giftdescription'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='letters',
            field=models.ManyToManyField(blank=True, help_text='letters involved in this episode', related_name='episodes', through='event.EpisodeLetter', to='letter.letterdescription'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='spaces',
            field=models.ManyToManyField(blank=True, help_text='locations involved in this episode', related_name='episodes', through='event.EpisodeSpace', to='space.spacedescription'),
        ),
    ]
