# Generated by Django 4.2.7 on 2024-09-26 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_fill_in_blank_sourcemention'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeagent',
            name='designators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant (Latin) terminology used to describe the entity in the episode', size=5),
        ),
        migrations.AddField(
            model_name='episodegift',
            name='designators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant (Latin) terminology used to describe the entity in the episode', size=5),
        ),
        migrations.AddField(
            model_name='episodeletter',
            name='designators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant (Latin) terminology used to describe the entity in the episode', size=5),
        ),
        migrations.AddField(
            model_name='episodespace',
            name='designators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant (Latin) terminology used to describe the entity in the episode', size=5),
        ),
        migrations.AlterField(
            model_name='episode',
            name='designators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant (Latin) terminology used to describe the actions in the episode', size=5),
        ),
    ]
