# Generated by Django 4.2.7 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_episode_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='episode',
            name='rank',
            field=models.IntegerField(default=0, help_text='The relative position of this description in the source'),
        ),
    ]
