# Generated by Django 4.2.7 on 2024-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_episode_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='episode',
            order_with_respect_to='source',
        ),
    ]
