# Generated by Django 4.2.7 on 2025-02-19 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0029_alter_episode_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', related_name='contributed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
