# Generated by Django 4.2.7 on 2024-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacedescription",
            name="ecclesiastical_regions",
            field=models.ManyToManyField(
                help_text="Ecclesiastical regions referenced in this description",
                through="space.EcclesiasticalRegionField",
                to="space.ecclesiasticalregion",
            ),
        ),
        migrations.AlterField(
            model_name="spacedescription",
            name="geographical_regions",
            field=models.ManyToManyField(
                help_text="Geographical regions referenced in this description",
                through="space.GeographicalRegionField",
                to="space.geographicalregion",
            ),
        ),
        migrations.AlterField(
            model_name="spacedescription",
            name="political_regions",
            field=models.ManyToManyField(
                help_text="Political regions referenced in this description",
                through="space.PoliticalRegionField",
                to="space.politicalregion",
            ),
        ),
        migrations.AlterField(
            model_name="spacedescription",
            name="structures",
            field=models.ManyToManyField(
                help_text="Man-made structures referenced in this description",
                through="space.StructureField",
                to="space.structure",
            ),
        ),
    ]
