# Generated by Django 4.2.7 on 2024-04-08 12:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_delete_reference'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is the entity presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='source',
            field=models.ForeignKey(default='', help_text='The source in which this description occurs.', on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='description',
            field=models.TextField(blank=True, help_text='longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable, meaning they (or it) can be cross-referenced between sources'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='name',
            field=models.CharField(help_text='a name to help identify this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='description',
            field=models.TextField(blank=True, help_text='longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable, meaning they (or it) can be cross-referenced between sources'),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='name',
            field=models.CharField(help_text='a name to help identify this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='description',
            field=models.TextField(blank=True, help_text='longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable, meaning they (or it) can be cross-referenced between sources'),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='name',
            field=models.CharField(help_text='a name to help identify this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='description',
            field=models.TextField(blank=True, help_text='longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='ecclesiastical_regions',
            field=models.ManyToManyField(help_text='Ecclesiastical regions referenced in this description', through='space.EcclesiasticalRegionField', to='space.ecclesiasticalregion'),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='geographical_regions',
            field=models.ManyToManyField(help_text='Geographical regions referenced in this description', through='space.GeographicalRegionField', to='space.geographicalregion'),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='name',
            field=models.CharField(help_text='a name to help identify this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='political_regions',
            field=models.ManyToManyField(help_text='Political regions referenced in this description', through='space.PoliticalRegionField', to='space.politicalregion'),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='structures',
            field=models.ManyToManyField(help_text='Man-made structures referenced in this description', through='space.StructureField', to='space.structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True, help_text='longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable, meaning they (or it) can be cross-referenced between sources'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(help_text='a name to help identify this object', max_length=128),
        ),
    ]
