# Generated by Django 4.2.7 on 2024-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_spacedescription_ecclesiastical_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='name',
            field=models.CharField(help_text='A name to identify this space when entering data', max_length=200),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description'),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='name',
            field=models.CharField(help_text='A name to identify this space when entering data', max_length=200),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description'),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='name',
            field=models.CharField(help_text='A name to identify this space when entering data', max_length=200),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='identifiable',
            field=models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(help_text='A name to identify this space when entering data', max_length=200),
        ),
    ]
