# Generated by Django 4.2.7 on 2024-03-27 10:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_delete_reference"),
        ("space", "0002_alter_spacedescription_ecclesiastical_regions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceDescriptionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name to identify this space when entering data",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Longer description of this place that can be used to identify it",
                    ),
                ),
                (
                    "ecclesiastical_regions",
                    models.ManyToManyField(
                        help_text="Ecclesiastical regions referenced in this description",
                        through="space.EcclesiasticalRegionField",
                        to="space.ecclesiasticalregion",
                    ),
                ),
                (
                    "geographical_regions",
                    models.ManyToManyField(
                        help_text="Geographical regions referenced in this description",
                        through="space.GeographicalRegionField",
                        to="space.geographicalregion",
                    ),
                ),
                (
                    "political_regions",
                    models.ManyToManyField(
                        help_text="Political regions referenced in this description",
                        through="space.PoliticalRegionField",
                        to="space.politicalregion",
                    ),
                ),
                (
                    "structures",
                    models.ManyToManyField(
                        help_text="Man-made structures referenced in this description",
                        through="space.StructureField",
                        to="space.structure",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="description",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="ecclesiastical_regions",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="geographical_regions",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="id",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="name",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="political_regions",
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="structures",
        ),
        migrations.AddField(
            model_name="spacedescription",
            name="spacedescriptionbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="space.spacedescriptionbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ecclesiasticalregionfield",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.AlterField(
            model_name="geographicalregionfield",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.AlterField(
            model_name="landscapefeature",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landscape_features",
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.AlterField(
            model_name="politicalregionfield",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.AlterField(
            model_name="structurefield",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.spacedescriptionbase",
            ),
        ),
        migrations.CreateModel(
            name="SpaceDescriptionDescription",
            fields=[
                (
                    "spacedescriptionbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="space.spacedescriptionbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="space.spacedescription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("space.spacedescriptionbase", models.Model),
        ),
    ]
