# Generated by Django 4.2.7 on 2024-04-09 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_spacedescription_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='ecclesiasticalregionfield',
            name='source_terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='geographicalregionfield',
            name='source_terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='landscapefeature',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='landscapefeature',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='landscapefeature',
            name='source_terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='politicalregionfield',
            name='source_terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this entity presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='source_location',
            field=models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='source_mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AddField(
            model_name='structurefield',
            name='source_terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticalregion',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='geographicalregion',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='politicalregion',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='spacedescription',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
    ]
