# Generated by Django 4.2.7 on 2024-04-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_placeholder_source'),
        ('space', '0007_ecclesiasticalregionfield_source_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacedescription',
            name='source',
            field=models.ForeignKey(help_text='Source text containing this description', on_delete=django.db.models.deletion.PROTECT, to='source.source'),
        ),
    ]
