# Generated by Django 4.2.7 on 2024-04-25 11:51

from django.db import migrations, models


def migrate_source_location_to_page(apps, schema_editor):
    SpaceDescription = apps.get_model("space", "SpaceDescription")
    for space_description in SpaceDescription.objects.all():
        if space_description.source_location:
            space_description.page = space_description.source_location
            space_description.save()


def migrate_page_to_source_location(apps, schema_editor):
    SpaceDescription = apps.get_model("space", "SpaceDescription")
    for space_description in SpaceDescription.objects.all():
        if space_description.page:
            space_description.source_location = space_description.page
            space_description.save()


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0008_alter_spacedescription_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacedescription",
            name="book",
            field=models.CharField(
                blank=True, help_text="The book in the source", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="spacedescription",
            name="chapter",
            field=models.CharField(
                blank=True,
                help_text="The chapter or chapters in the source",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="spacedescription",
            name="page",
            field=models.CharField(
                blank=True,
                help_text="The page number or page range in the source",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            code=migrate_source_location_to_page,
            reverse_code=migrate_page_to_source_location,
        ),
        migrations.RemoveField(
            model_name="spacedescription",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="ecclesiasticalregionfield",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="geographicalregionfield",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="landscapefeature",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="politicalregionfield",
            name="source_location",
        ),
        migrations.RemoveField(
            model_name="structurefield",
            name="source_location",
        ),
    ]
