# Generated by Django 4.2.7 on 2024-05-17 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0009_remove_spacedescription_source_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecclesiasticalregionfield",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="geographicalregionfield",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="landscapefeature",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="politicalregionfield",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="structurefield",
            name="source_terminology",
        ),
        migrations.AddField(
            model_name="spacedescription",
            name="designators",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Relevant (Latin) terminology used to describe this entity in the source text",
                size=5,
            ),
        ),
    ]
