# Generated by Django 4.2.7 on 2024-06-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_merge_region_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('identifiable', models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.settlement')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.spacedescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spacedescription',
            name='settlements',
            field=models.ManyToManyField(help_text='Settlements referenced in this description', through='space.SettlementField', to='space.settlement'),
        ),
        migrations.AddField(
            model_name='structure',
            name='settlement',
            field=models.ForeignKey(blank=True, help_text='The settlement containing this structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='space.settlement'),
        ),
    ]
