# Generated by Django 4.2.7 on 2024-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0013_move_settlement_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='parent',
        ),
        migrations.AlterField(
            model_name='structure',
            name='level',
            field=models.IntegerField(choices=[(1, 'road, square, crossroad'), (2, 'fortification'), (3, 'building, vessel'), (4, 'room'), (5, 'spot, object')]),
        ),
    ]
