# Generated by Django 4.2.7 on 2024-06-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0014_remove_structure_parent_alter_structure_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandscapeFeature',
        ),
    ]
