# Generated by Django 4.2.7 on 2024-06-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0015_delete_landscapefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Surrounding regions of this settlement', related_name='settlements', to='space.region'),
        ),
    ]
