# Generated by Django 4.2.7 on 2024-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0017_region_contributors_settlement_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionfield',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='settlementfield',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='structurefield',
            name='source_mention',
            field=models.CharField(choices=[('direct', 'directly mentioned'), ('implied', 'implied')], default='direct', help_text='How is this information presented in the text?', max_length=32),
        ),
    ]
