# Generated by Django 4.2.7 on 2024-09-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0018_alter_regionfield_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacedescription',
            options={'ordering': [models.OrderBy(models.Case(models.When(structures__identifiable=True, then=1), models.When(settlements__identifiable=True, then=2), models.When(regions__identifiable=True, then=3), default=None), nulls_last=True)]},
        ),
    ]
