# Generated by Django 4.2.7 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0021_alter_regionfield_source_mention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacedescription',
            name='rank',
            field=models.IntegerField(default=0, help_text='The relative position of this description in the source'),
        ),
    ]
