# Generated by Django 4.2.7 on 2024-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='a unique name to identify this source in the database', max_length=200, unique=True)),
                ('bibliographical_info', models.TextField(blank=True, help_text='bibliographical information to identify this source')),
            ],
        ),
    ]
