# Generated by Django 4.2.7 on 2024-02-09 13:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, help_text='specific location of the reference in the source text', max_length=200)),
                ('terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], help_text='terminology used in the source text to describe this entity', size=5)),
                ('mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='how is this entity presented in the text?', max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('source', models.ForeignKey(help_text='the source text in which this references occurs', on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='source_refe_content_816b0e_idx')],
            },
        ),
    ]
