# Generated by Django 4.2.7 on 2024-02-16 10:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location of the reference in the source text', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='mention',
            field=models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32),
        ),
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.ForeignKey(help_text='The source text in which this references occurs', on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='terminology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Terminology used in the source text to describe this entity', size=5),
        ),
    ]
