# Generated by Django 4.2.7 on 2024-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0003_alter_reference_location_alter_reference_mention_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reference",
        ),
    ]
