# Generated by Django 4.2.7 on 2024-04-09 10:55

from django.db import migrations


def create_placeholder_source(apps, schema_editor):
    Source = apps.get_model("source", "Source")
    Source.objects.create(
        name="MISSING SOURCE",
        bibliographical_info="This is a placeholder value for older data that is missing source information",
    )


def remove_placeholder_source(apps, schema_editor):
    Source = apps.get_model("source", "Source")
    placeholder = Source.objects.filter(name="MISSING SOURCE")
    if placeholder.exists():
        placeholder.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_delete_reference"),
    ]

    operations = [
        migrations.RunPython(
            create_placeholder_source,
            reverse_code=remove_placeholder_source,
        )
    ]
