# Generated by Django 4.2.7 on 2024-04-25 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def migrate_bibliographical_info_to_edition_title(apps, schema_editor):
    Source = apps.get_model("source", "Source")
    for source in Source.objects.all():
        if source.bibliographical_info:
            source.edition_title = source.bibliographical_info
            source.save()


def migrate_source_fields_to_bibliographical_info(apps, schema_editor):
    Source = apps.get_model("source", "Source")
    for source in Source.objects.all():
        if source.medieval_title:
            source.bibliographical_info += f" {source.medieval_title}"
        if source.medieval_author:
            source.bibliographical_info += f" {source.medieval_author}"
        if source.edition_title:
            source.bibliographical_info += f" {source.edition_title}"
        if source.edition_author:
            source.bibliographical_info += f" {source.edition_author}"
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0005_placeholder_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="edition_author",
            field=models.CharField(
                blank=True,
                help_text="The name of the author of the edition",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="edition_title",
            field=models.CharField(
                blank=True,
                help_text="The title of the edition used for this source",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="medieval_author",
            field=models.CharField(
                blank=True,
                help_text="The name of the original author of the work, if known",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="medieval_title",
            field=models.CharField(
                blank=True,
                help_text="The original title of the work, if known",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            code=migrate_bibliographical_info_to_edition_title,
            reverse_code=migrate_source_fields_to_bibliographical_info,
        ),
        migrations.RemoveField(
            model_name="source",
            name="bibliographical_info",
        ),
        migrations.CreateModel(
            name="SourceWrittenDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_lower",
                    models.IntegerField(
                        default=400,
                        help_text="The earliest possible year for this value",
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "year_upper",
                    models.IntegerField(
                        default=800,
                        help_text="The latest possible year for this value",
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "year_exact",
                    models.IntegerField(
                        blank=True,
                        help_text="The exact year of the value (if known). This will override the values in the lower and upper bounds fields.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        help_text="The source that was written at this date",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_date",
                        to="source.source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceContentsDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_lower",
                    models.IntegerField(
                        default=400,
                        help_text="The earliest possible year for this value",
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "year_upper",
                    models.IntegerField(
                        default=800,
                        help_text="The latest possible year for this value",
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "year_exact",
                    models.IntegerField(
                        blank=True,
                        help_text="The exact year of the value (if known). This will override the values in the lower and upper bounds fields.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        help_text="The source whose events took place at this date",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents_date",
                        to="source.source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
