# Generated by Django 4.2.7 on 2025-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_source_edition_author_source_edition_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this source is available in the browsing interface or not.'),
        ),
    ]
