# Generated by Django 4.2.7 on 2025-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('source', '0006_source_edition_author_source_edition_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='User groups that can edit the source', related_name='sources', to='auth.group'),
        ),
    ]
