# Generated by Django 4.2.7 on 2025-07-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_source_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description_text',
            field=models.TextField(blank=True, help_text='Background information about the text'),
        ),
        migrations.AddField(
            model_name='source',
            name='reference',
            field=models.TextField(blank=True, help_text='Bibliographical reference to the text', verbose_name='bibliographical reference'),
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to be displayed on the source page', upload_to='source_images/')),
                ('alt_text', models.CharField(help_text='Brief description of the image contents; shown when the image cannot be displayed', max_length=256, verbose_name='Text alternative')),
                ('caption', models.TextField(help_text='Image caption; shown below the image', max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='source.source')),
            ],
        ),
    ]
