# Generated by Django 4.2.7 on 2025-07-08 15:44

from django.db import migrations
import re

def move_data_to_description(apps, schema_editor):
    Source = apps.get_model('source', 'Source')
    for source in Source.objects.all():
        source.description_text =  \
            f'Source: {source.medieval_title}, {source.medieval_author}\n' \
            f'Edition: {source.edition_title}, {source.edition_author}'
        source.save()

def move_data_to_fields(apps, schema_editor):
    Source = apps.get_model('source', 'Source')
    pattern = re.compile(r'Source: (.+), (.+)\nEdition: (.+), (.+)')
    for source in Source.objects.all():
        if match := re.search(pattern, source.description_text or ''):
            medieval_title, medieval_author, edition_title, edition_author = match.groups()
            source.medieval_title = medieval_title
            source.medieval_author = medieval_author
            source.edition_title = edition_title
            source.edition_author = edition_author
            source.save()

class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_add_source_description_reference_and_more'),
    ]

    operations = [
        migrations.RunPython(
            move_data_to_description,
            reverse_code=move_data_to_fields,
        ),
    ]
