# Generated by Django 4.2.7 on 2025-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_migrate_edition_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='edition_author',
        ),
        migrations.RemoveField(
            model_name='source',
            name='edition_title',
        ),
        migrations.RemoveField(
            model_name='source',
            name='medieval_author',
        ),
        migrations.AlterField(
            model_name='source',
            name='medieval_title',
            field=models.CharField(blank=True, help_text='The original (Latin) title of the work', max_length=255),
        ),
    ]
