# Generated by Django 4.2.30 on 2026-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256)),
                ('category', models.IntegerField(choices=[(1, 'Letters'), (2, 'Gifts'), (3, 'Messengers'), (4, 'Actions')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'term'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name used in the index (and for citations)', max_length=256)),
                ('category', models.IntegerField(choices=[(1, 'Primary'), (2, 'Reference'), (3, 'Secondary')])),
                ('reference', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
