# Generated by Django 4.2.7 on 2024-04-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user_profile(apps, schema_editor):
    User = apps.get_model("user", "User")
    UserProfile = apps.get_model("user", "UserProfile")

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            add_user_profile,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
