# Generated by Django 4.2.7 on 2024-04-23 11:14

from django.db import migrations


def add_verified_primary_email(apps, schema_editor):
    """
    Ensures all users have a primary email address and marks it as verified

    This ensures existing users will not be locked out of their account when
    email verification becomes required
    """

    User = apps.get_model("user", "User")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for user in User.objects.all():
        secondary_emails = EmailAddress.objects.filter(user=user).exclude(
            email=user.email
        )
        for email in secondary_emails:
            email.primary = False
            email.save()

        email, _ = EmailAddress.objects.get_or_create(user=user, email=user.email)
        email.verified = True
        email.primary = True
        email.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_verified_primary_email,
            reverse_code=migrations.RunPython.noop,
        )
    ]
