# Generated by Django 4.2.7 on 2025-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_contributor',
        ),
    ]
