# Generated by Django 4.2.7 on 2025-10-20 13:23

from django.db import migrations

def add_user_profiles(apps, schema_editor):
    '''Create a user profile for all existing users'''

    User = apps.get_model('user', 'User')
    UserProfile = apps.get_model('user', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contributorrole_userprofile'),
    ]

    operations = [
        migrations.RunPython(add_user_profiles, reverse_code=migrations.RunPython.noop)
    ]
