# Generated by Django 4.2.7 on 2025-10-20 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role in which this user should be credited (e.g. project leader, research assistant). Users without a contributor role are not visible tovisitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.contributorrole'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
