# Generated by Django 4.2.7 on 2025-10-21 11:34

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.UserProfile.image_upload_path),
        ),
    ]
