# Generated by Django 4.2.7 on 2025-10-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role in which this user should be credited (e.g. project leader, research assistant). Users without a contributor role are not visible tovisitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='user.contributorrole'),
        ),
    ]
