# Generated by Django 4.2.30 on 2026-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name_prefix',
            field=models.CharField(default='', help_text='Tussenvoegsel for Dutch localised names', max_length=64),
        ),
    ]
