# Generated by Django 4.2.30 on 2026-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_last_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name_prefix',
            field=models.CharField(blank=True, default='', help_text='Tussenvoegsel for Dutch localised names', max_length=64),
        ),
    ]
