# Generated by Django 4.2.7 on 2024-01-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LetterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('surface', models.CharField(choices=[('parchment', 'parchment'), ('papyrus', 'papyrus'), ('other', 'other'), ('unknown', 'unknown')])),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letter.letter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
