# Generated by Django 4.2.7 on 2024-01-31 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("letter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="letter",
            name="name",
            field=models.CharField(
                help_text="a unique name to identify this letter in the database",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LetterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certainty",
                    models.IntegerField(
                        choices=[
                            (0, "uncertain"),
                            (1, "somewhat certain"),
                            (2, "certain"),
                        ],
                        default=2,
                        help_text="How certain are you of this value?",
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="letter.category",
                    ),
                ),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="letter.letter"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
