# Generated by Django 4.2.7 on 2024-01-31 17:03

from django.db import migrations


def generate_name(apps, schema_editor):
    Letter = apps.get_model("letter", "Letter")
    for row in Letter.objects.all():
        row.name = f"letter #{row.id}"
        row.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("letter", "0002_category_letter_name_lettercategory"),
    ]

    operations = [
        migrations.RunPython(generate_name, reverse_code=migrations.RunPython.noop)
    ]
