# Generated by Django 4.2.7 on 2024-01-31 17:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("letter", "0003_populate_letter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="name",
            field=models.CharField(
                help_text="a unique name to identify this letter in the database",
                max_length=200,
                unique=True,
            ),
        ),
    ]
