# Generated by Django 4.2.7 on 2024-02-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('letter', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letter.letter')),
                ('senders', models.ManyToManyField(blank=True, help_text='persons that the letter names as the sender', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterAddressees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('addressees', models.ManyToManyField(blank=True, help_text='persons that the letter names as the addressee', to='person.person')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letter.letter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
