# Generated by Django 4.2.7 on 2024-03-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_socialstatus_person_and_more'),
        ('letter', '0007_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gifted_by',
            field=models.ForeignKey(blank=True, help_text='The agent who gave the gift. Leave empty if unknown.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given', to='person.person'),
        ),
        migrations.AlterField(
            model_name='letteraddressees',
            name='addressees',
            field=models.ManyToManyField(blank=True, help_text='Agents whom the letter names as the addressee', to='person.person'),
        ),
        migrations.AlterField(
            model_name='lettersenders',
            name='senders',
            field=models.ManyToManyField(blank=True, help_text='Agents whom the letter names as the sender', to='person.person'),
        ),
    ]
