# Generated by Django 4.2.7 on 2024-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0008_alter_gift_gifted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A short name for the gift (for identification)",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A longer description of the gift"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("precious metal", "precious metal"),
                            ("textile", "textile"),
                            ("wood", "wood"),
                            ("glass", "glass"),
                            ("ceramic", "ceramic"),
                            ("animal product", "animal product"),
                            ("livestock", "livestock"),
                            ("paper", "paper"),
                            ("other", "other"),
                            ("unknown", "unknown"),
                        ],
                        help_text="The material the gift consists of",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetterBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="a unique name to identify this letter in the database",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="gift",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="gifted_by",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="material",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="name",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="name",
        ),
    ]
