# Generated by Django 4.2.7 on 2024-03-27 20:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0012_agentbase_remove_agent_gender_group_constraint_and_more"),
        ("source", "0004_delete_reference"),
        ("letter", "0008_alter_gift_gifted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A short name for the gift (for identification)",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A longer description of the gift"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("precious metal", "precious metal"),
                            ("textile", "textile"),
                            ("wood", "wood"),
                            ("glass", "glass"),
                            ("ceramic", "ceramic"),
                            ("animal product", "animal product"),
                            ("livestock", "livestock"),
                            ("paper", "paper"),
                            ("other", "other"),
                            ("unknown", "unknown"),
                        ],
                        help_text="The material the gift consists of",
                    ),
                ),
                (
                    "gifted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agent who gave the gift. Leave empty if unknown.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_given",
                        to="person.agentbase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetterBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="a unique name to identify this letter in the database",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="gift",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="gifted_by",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="material",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="name",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="id",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="name",
        ),
        migrations.AlterField(
            model_name="letteraddressees",
            name="addressees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents whom the letter names as the addressee",
                to="person.agentbase",
            ),
        ),
        migrations.AlterField(
            model_name="lettersenders",
            name="senders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents whom the letter names as the sender",
                to="person.agentbase",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="giftbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="letter.giftbase",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="letterbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="letter.letterbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="letteraddressees",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettercategory",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettermaterial",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettersenders",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.CreateModel(
            name="LetterDescription",
            fields=[
                (
                    "letterbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="letter.letterbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="letter.letter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("letter.letterbase", models.Model),
        ),
        migrations.CreateModel(
            name="GiftDescription",
            fields=[
                (
                    "giftbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="letter.giftbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="letter.giftbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("letter.giftbase", models.Model),
        ),
    ]
