# Generated by Django 4.2.7 on 2024-04-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_alter_gift_gifted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettersenders',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='lettersenders',
            name='senders',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='gifted_by',
        ),
        migrations.DeleteModel(
            name='LetterAddressees',
        ),
        migrations.DeleteModel(
            name='LetterSenders',
        ),
    ]
