# Generated by Django 4.2.7 on 2024-03-27 10:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_delete_reference"),
        ("person", "0012_agentbase_remove_agent_gender_group_constraint_and_more"),
        ("letter", "0009_giftbase_letterbase_remove_gift_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letteraddressees",
            name="addressees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents whom the letter names as the addressee",
                to="person.agentbase",
            ),
        ),
        migrations.AlterField(
            model_name="lettersenders",
            name="senders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents whom the letter names as the sender",
                to="person.agentbase",
            ),
        ),
        migrations.AddField(
            model_name="giftbase",
            name="gifted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The agent who gave the gift. Leave empty if unknown.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_given",
                to="person.agentbase",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="giftbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="letter.giftbase",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="letterbase_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="letter.letterbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="letteraddressees",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettercategory",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettermaterial",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.AlterField(
            model_name="lettersenders",
            name="letter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="letter.letterbase"
            ),
        ),
        migrations.CreateModel(
            name="LetterDescription",
            fields=[
                (
                    "letterbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="letter.letterbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="letter.letter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("letter.letterbase", models.Model),
        ),
        migrations.CreateModel(
            name="GiftDescription",
            fields=[
                (
                    "giftbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="letter.giftbase",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location of the reference in the source text",
                        max_length=200,
                    ),
                ),
                (
                    "terminology",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terminology used in the source text to describe this entity",
                        size=5,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "directly mentioned"),
                            ("implied", "implied"),
                        ],
                        help_text="How is this information presented in the text?",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source in which this description occurs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="source.source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_descriptions",
                        to="letter.giftbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("letter.giftbase", models.Model),
        ),
    ]
