# Generated by Django 4.2.7 on 2024-04-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_letteraction_gifts_and_more'),
        ('letter', '0009_remove_lettersenders_letter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.RemoveField(
            model_name='lettercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lettercategory',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='lettermaterial',
            name='letter',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='LetterCategory',
        ),
        migrations.DeleteModel(
            name='LetterMaterial',
        ),
    ]
