# Generated by Django 4.2.7 on 2024-04-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_agentdescription_agentgender_person_and_more'),
        ('source', '0004_delete_reference'),
        ('letter', '0010_giftaddressee_agent_giftaddressee_gift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftaddressee',
            name='agent',
            field=models.ForeignKey(help_text='agent described as an addressee of the gift', on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription'),
        ),
        migrations.AlterField(
            model_name='giftaddressee',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription'),
        ),
        migrations.AlterField(
            model_name='giftdescription',
            name='source',
            field=models.ForeignKey(help_text='The source in which this description occurs.', on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
        migrations.AlterField(
            model_name='giftmaterial',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='letter.giftdescription'),
        ),
        migrations.AlterField(
            model_name='giftsender',
            name='agent',
            field=models.ForeignKey(help_text='agent described as a sender of the gift', on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription'),
        ),
        migrations.AlterField(
            model_name='giftsender',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription'),
        ),
        migrations.AlterField(
            model_name='letteraddressee',
            name='agent',
            field=models.ForeignKey(help_text='agent described as an addressee of the letter', on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription'),
        ),
        migrations.AlterField(
            model_name='letteraddressee',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription'),
        ),
        migrations.AlterField(
            model_name='letterdescription',
            name='source',
            field=models.ForeignKey(help_text='The source in which this description occurs.', on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
        migrations.AlterField(
            model_name='lettersender',
            name='agent',
            field=models.ForeignKey(help_text='agent described as a sender of the letter', on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription'),
        ),
        migrations.AlterField(
            model_name='lettersender',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription'),
        ),
        migrations.AlterField(
            model_name='preservedletterrole',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.preservedletter'),
        ),
        migrations.AlterField(
            model_name='preservedletterrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
