# Generated by Django 4.2.7 on 2024-04-11 11:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_alter_persondateofbirth_person_and_more'),
        ('source', '0005_placeholder_source'),
        ('letter', '0010_delete_gift_remove_lettercategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
            ],
            options={
                'verbose_name_plural': 'gift categories',
            },
        ),
        migrations.CreateModel(
            name='GiftDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this entity presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this entity presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location(s) where the entity is mentioned or described in the source text', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterDescriptionSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterDescriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.category')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterDescriptionAddressee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.letterdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='addressees',
            field=models.ManyToManyField(related_name='letters_addressed', through='letter.LetterDescriptionAddressee', to='person.agentdescription'),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='categories',
            field=models.ManyToManyField(through='letter.LetterDescriptionCategory', to='letter.category'),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='senders',
            field=models.ManyToManyField(related_name='letters_sent', through='letter.LetterDescriptionSender', to='person.agentdescription'),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='source',
            field=models.ForeignKey(help_text='Source text containing this description', on_delete=django.db.models.deletion.PROTECT, to='source.source'),
        ),
        migrations.CreateModel(
            name='GiftDescriptionSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftDescriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftcategory')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftDescriptionAddressee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('source_mention', models.CharField(blank=True, choices=[('direct', 'directly mentioned'), ('implied', 'implied')], help_text='How is this information presented in the text?', max_length=32)),
                ('source_location', models.CharField(blank=True, help_text='Specific location of the information in the source text', max_length=200)),
                ('source_terminology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Relevant terminology used in the source text', size=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.agentdescription')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.giftdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='addressees',
            field=models.ManyToManyField(related_name='gifts_addressed', through='letter.GiftDescriptionAddressee', to='person.agentdescription'),
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='categories',
            field=models.ManyToManyField(through='letter.GiftDescriptionCategory', to='letter.giftcategory'),
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='senders',
            field=models.ManyToManyField(related_name='gifts_sent', through='letter.GiftDescriptionSender', to='person.agentdescription'),
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='source',
            field=models.ForeignKey(help_text='Source text containing this description', on_delete=django.db.models.deletion.PROTECT, to='source.source'),
        ),
    ]
