# Generated by Django 4.2.7 on 2024-04-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_alter_persondateofbirth_person_and_more'),
        ('letter', '0011_giftcategory_giftdescription_letterdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('identifiable', models.BooleanField(default=True, help_text='Whether this entity is identifiable (i.e. can be cross-referenced between descriptions), or a generic description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreservedLetterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certainty', models.IntegerField(choices=[(0, 'uncertain'), (1, 'somewhat certain'), (2, 'certain')], default=2, help_text='How certain are you of this value?')),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.preservedletter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.historicalperson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='preservedletter',
            name='persons_involved',
            field=models.ManyToManyField(blank=True, help_text='historical figures related to the letter', through='letter.PreservedLetterRole', to='person.historicalperson'),
        ),
    ]
