# Generated by Django 4.2.7 on 2024-05-17 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0013_remove_giftdescription_source_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftdescriptionaddressee",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="giftdescriptioncategory",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="giftdescriptionsender",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionaddressee",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="letterdescriptioncategory",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionsender",
            name="source_terminology",
        ),
        migrations.AddField(
            model_name="giftdescription",
            name="designators",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Relevant (Latin) terminology used to describe this entity in the source text",
                size=5,
            ),
        ),
        migrations.AddField(
            model_name="letterdescription",
            name="designators",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Relevant (Latin) terminology used to describe this entity in the source text",
                size=5,
            ),
        ),
    ]
