# Generated by Django 4.2.7 on 2024-05-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0014_remove_giftdescriptionaddressee_source_terminology_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftdescriptionsender",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="giftdescriptionsender",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionaddressee",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionaddressee",
            name="letter",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionsender",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="letterdescriptionsender",
            name="letter",
        ),
        migrations.RemoveField(
            model_name="giftdescription",
            name="addressees",
        ),
        migrations.RemoveField(
            model_name="giftdescription",
            name="senders",
        ),
        migrations.RemoveField(
            model_name="letterdescription",
            name="addressees",
        ),
        migrations.RemoveField(
            model_name="letterdescription",
            name="senders",
        ),
        migrations.DeleteModel(
            name="GiftDescriptionAddressee",
        ),
        migrations.DeleteModel(
            name="GiftDescriptionSender",
        ),
        migrations.DeleteModel(
            name="LetterDescriptionAddressee",
        ),
        migrations.DeleteModel(
            name="LetterDescriptionSender",
        ),
    ]
