# Generated by Django 4.2.7 on 2024-07-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0015_remove_giftdescriptionsender_agent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="LetterCategory",
        ),
    ]
