# Generated by Django 4.2.7 on 2024-08-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0017_alter_giftdescriptioncategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdescription',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preservedletter',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
