# Generated by Django 4.2.7 on 2024-09-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0019_alter_giftdescriptioncategory_source_mention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftdescription',
            name='designators',
        ),
        migrations.RemoveField(
            model_name='letterdescription',
            name='designators',
        ),
    ]
