# Generated by Django 4.2.7 on 2024-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0021_alter_giftdescription_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='giftdescription',
            order_with_respect_to='source',
        ),
        migrations.AlterOrderWithRespectTo(
            name='letterdescription',
            order_with_respect_to='source',
        ),
    ]
