# Generated by Django 4.2.7 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0021_alter_giftdescription_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftdescription',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='letterdescription',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='rank',
            field=models.IntegerField(default=0, help_text='The relative position of this description in the source'),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='rank',
            field=models.IntegerField(default=0, help_text='The relative position of this description in the source'),
        ),
    ]
