# Generated by Django 4.2.7 on 2025-02-19 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0022_alter_giftdescription_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdescription',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', related_name='contributed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letterdescription',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Users who contributed to this entry', related_name='contributed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
