# Generated by Django 4.2.7 on 2025-03-28 10:43

import uuid
from django.db import migrations, models


def migrate_name_to_label(apps, schema_editor):
    """
    Migrates the value of the non-unique, nullable 'name' field to a new unique, non-nullable 'label' field.

    If the name is empty or not unique, use UUID to generate a unique label.
    """
    GiftCategory = apps.get_model("letter", "GiftCategory")

    def generate_unique_id() -> str:
        return str(uuid.uuid4())

    # Keep track of used labels.
    used_labels = set()

    for category in GiftCategory.objects.all():
        if category.name and category.name not in used_labels:
            category.label = category.name
            used_labels.add(category.name)
        else:
            category.label = f"Missing-label-{generate_unique_id()}"

        category.save()


def migrate_label_to_name(apps, schema_editor):
    """
    Reverse migration: puts the value of `label` back into `name`.
    """
    GiftCategory = apps.get_model("letter", "GiftCategory")

    # Revert label to name if needed, or handle as per your requirements.
    for category in GiftCategory.objects.all():
        category.name = category.label or ""
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0023_alter_giftdescription_contributors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftcategory",
            options={
                "verbose_name": "gift category",
                "verbose_name_plural": "gift categories",
            },
        ),
        # Set a default value so the reverse migration works.
        migrations.AlterField(
            model_name="giftcategory",
            name="name",
            field=models.CharField(max_length=200, default=""),
        ),
        # Temporarily allow null to facilitate the transfer from 'name' to 'label'.
        migrations.AddField(
            model_name="giftcategory",
            name="label",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunPython(
            code=migrate_name_to_label,
            reverse_code=migrate_label_to_name,  # No reverse migration
        ),
        # Make label non-nullable and unique.
        migrations.AlterField(
            model_name="giftcategory",
            name="label",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="giftcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="giftcategory",
            name="name",
        ),
    ]
