# Generated by Django 4.2.7 on 2025-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0024_alter_giftcategory_options_remove_giftcategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterdescriptioncategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='letterdescriptioncategory',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='giftdescription',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='letterdescription',
            name='categories',
        ),
        migrations.DeleteModel(
            name='GiftDescriptionCategory',
        ),
        migrations.DeleteModel(
            name='LetterDescriptionCategory',
        ),
        migrations.AddField(
            model_name='giftdescription',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='categories assigned to the gift', related_name='gifts', to='letter.giftcategory'),
        ),
        migrations.AddField(
            model_name='letterdescription',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='categories assigned to the letter', related_name='letters', to='letter.lettercategory'),
        ),
    ]
