# Generated by Django 4.2.7 on 2024-02-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personname',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='person.person'),
        ),
        migrations.AddConstraint(
            model_name='personname',
            constraint=models.UniqueConstraint(models.F('value'), models.F('person'), name='unique_names_for_person'),
        ),
    ]
