# Generated by Django 4.2.7 on 2024-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_persondateofdeath_persondateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_group',
            field=models.BooleanField(default=False, help_text="Check if this entity is a group of people (e.g. 'the nuns of Poitiers'). If checked, leave the Date of Birth and Date of Death fields empty."),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True, help_text="A description of what the marker means (e.g. 'The bishop of Toulouse is the ecclesiastical ruler of the diocese of Toulouse')"),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(help_text="The name of the marker or job (e.g. 'bishop of Toulouse', 'peasantry of France')", max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNKNOWN', 'Unknown'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='UNKNOWN', help_text='The gender of this person or the group members. The option Mixed is only used for groups.', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('gender', 'MIXED'), ('is_group', True), _negated=True), name='gender_group_constraint', violation_error_message="The 'mixed' gender option is reserved for groups"),
        ),
    ]
