# Generated by Django 4.2.7 on 2024-03-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_rename_office_statusmarker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupation',
            new_name='SocialStatus',
        ),
        migrations.RenameField(
            model_name='socialstatus',
            old_name='office',
            new_name='status_marker',
        ),
    ]
