# Generated by Django 4.2.7 on 2024-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_person_role_agent_alter_role_description_and_more'),
        ('letter', '0008_alter_gift_gifted_by_and_more'),
        ('person', '0008_alter_socialstatus_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Agent',
        ),
        migrations.RenameModel(
            old_name='PersonDateOfBirth',
            new_name='AgentDateOfBirth',
        ),
        migrations.RenameModel(
            old_name='PersonDateOfDeath',
            new_name='AgentDateOfDeath',
        ),
        migrations.RenameModel(
            old_name='PersonName',
            new_name='AgentName',
        ),
        migrations.RemoveConstraint(
            model_name='agentname',
            name='unique_names_for_person',
        ),
        migrations.AddConstraint(
            model_name='agentname',
            constraint=models.UniqueConstraint(models.F('value'), models.F('person'), name='unique_names_for_agent'),
        ),
    ]
