# Generated by Django 4.2.7 on 2024-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_rename_person_agent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentname',
            name='unique_names_for_agent',
        ),
        migrations.RenameField(
            model_name='agentdateofbirth',
            old_name='person',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='agentdateofdeath',
            old_name='person',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='agentname',
            old_name='person',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='socialstatus',
            old_name='person',
            new_name='agent',
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNKNOWN', 'Unknown'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='UNKNOWN', help_text='The gender of this agent or group of agents. The option Mixed is only used for groups.', max_length=8),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_group',
            field=models.BooleanField(default=False, help_text="Check if this entity is a group of agents (e.g. 'the nuns of Poitiers'). If checked, the date of birth and date of death fields should be left empty."),
        ),
        migrations.AddConstraint(
            model_name='agentname',
            constraint=models.UniqueConstraint(models.F('value'), models.F('agent'), name='unique_names_for_agent'),
        ),
    ]
