# Generated by Django 4.2.7 on 2024-03-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0010_remove_agentname_unique_names_for_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("UNKNOWN", "Unknown"),
                    ("MIXED", "Mixed"),
                    ("OTHER", "Other"),
                ],
                default="UNKNOWN",
                help_text="The gender of this person or group of people. The option Mixed is only used for groups.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="Whether this entity is a group of people (e.g. 'the nuns of Poitiers'). If true, the date of birth and date of death fields should be left empty.",
            ),
        ),
        migrations.AlterField(
            model_name="agentdateofbirth",
            name="agent",
            field=models.OneToOneField(
                limit_choices_to={"is_group": False},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_of_birth",
                to="person.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentdateofdeath",
            name="agent",
            field=models.OneToOneField(
                limit_choices_to={"is_group": False},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_of_death",
                to="person.agent",
            ),
        ),
    ]
