# Generated by Django 4.2.7 on 2024-05-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0015_remove_agentdescription_source_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentDescriptionSocialStatus",
        ),
        migrations.DeleteModel(
            name="StatusMarker",
        ),
    ]
