# Generated by Django 4.2.7 on 2024-05-17 13:15

import django.contrib.postgres.fields
from django.db import migrations, models

def migrate_names_to_designators(apps, schema_editor):
    AgentDescription = apps.get_model("person", "AgentDescription")
    for agent_description in AgentDescription.objects.all():
        if agent_description.names:
            agent_description.designators = list(agent_description.names.values_list("name", flat=True))
            agent_description.save()

class Migration(migrations.Migration):

    dependencies = [
        ("person", "0015_remove_agentdescription_source_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentdescriptiongender",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="agentdescriptionlocation",
            name="source_terminology",
        ),
        migrations.RemoveField(
            model_name="agentdescriptionsocialstatus",
            name="source_terminology",
        ),
        migrations.AddField(
            model_name="agentdescription",
            name="designators",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Relevant (Latin) terminology used to describe this entity in the source text",
                size=5,
            ),
        ),
        migrations.RunPython(code=migrate_names_to_designators, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name="AgentDescriptionName",
        ),
    ]
