# Generated by Django 4.2.7 on 2024-05-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0016_remove_agentdescriptiongender_source_terminology_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentDescriptionSocialStatus",
        ),
        migrations.DeleteModel(
            name="StatusMarker",
        ),
    ]
