# Generated by Django 4.2.7 on 2024-06-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0017_delete_agentdescriptionsocialstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personreference",
            name="description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_references",
                to="person.agentdescription",
            ),
        ),
        migrations.AlterField(
            model_name="personreference",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description_references",
                to="person.historicalperson",
            ),
        ),
    ]
