# Generated by Django 4.2.7 on 2024-08-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_alter_personreference_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdescriptionlocation',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='person.agentdescription'),
        ),
    ]
