# Generated by Django 4.2.7 on 2024-09-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_alter_agentdescriptiongender_source_mention_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentdescription',
            options={'ordering': [models.OrderBy(models.F('describes__identifiable'), descending=True, nulls_last=True), 'is_group']},
        ),
    ]
