gift_names = [
    "Handcrafted leather journal",
    "Ornate quill and ink set",
    "Medieval-style tapestry",
    "Wooden goblet set",
    "Customized family crest",
    "Illuminated manuscript reproduction",
    "Historical board game set",
    "Hand-forged iron candle holder",
    "Potion-making kit",
    "Medieval-inspired chess set",
    "Viking drinking horn",
    "Chainmail jewelry",
    "Archery lessons",
    "Medieval-style feast cookbook",
    "Hand-carved wooden tankard",
    "Medieval music instrument set",
    "Renaissance-style clothing",
    "Falconry experience",
    "Historical map reproduction",
    "Custom-made medieval armor display",
    "Stained glass window art",
    "Herb garden starter kit",
    "Medieval-themed puzzle",
    "Blacksmithing workshop",
    "Wax sealing kit",
    "Leather-bound spell book",
    "Antique-style compass",
    "Hand-painted medieval miniature figurines",
    "Knights and dragons chessboard",
    "Scribe calligraphy set",
    "Chainmail dice bag",
    "Medieval-style drinking game set",
    "Handmade medieval soap set",
    "Armor-shaped cookie cutter set",
    "Castle-shaped candle holder",
    "Medieval-themed tarot cards",
    "Historical weapon replicas",
    "Hand-blown glass potion bottles",
    "Jousting tournament tickets",
    "Illuminated letter initial necklace",
    "Medieval-style tapestry throw blanket",
    "Renaissance fair tickets",
    "Historical reenactment workshop",
    "Falcon-shaped cookie jar",
    "Viking ship model kit",
    "Medieval flag/banner",
    "Dragon-themed quill holder",
    "Hand-carved wooden chest",
    "Medieval-themed puzzle book",
    "Archery target practice set",
    "Medieval-style goblet charm bracelet",
    "Old-world recipe ingredients",
    "Illuminated letter wine glasses",
    "Medieval-themed wall clock",
    "Handmade leather pouch",
    "Antique-style world map puzzle",
    "Engraved armor-shaped flask",
    "Heraldic shield wall plaque",
    "Historical costume sewing kit",
    "Medieval-themed playing cards",
    "Dragon-shaped candle",
    "Medieval-style coin collection",
    "Knight helmet ice mold",
    "Embroidery starter kit",
    "Leather-bound potion recipe book",
    "Hand-painted medieval shield",
    "Themed jigsaw puzzle",
    "Medieval coin necklace",
    "Leather armor care kit",
    "Dragon-shaped incense holder",
    "Medieval-style flagon",
    "Chainmail dice bag necklace",
    "Historical battle reenactment tickets",
    "Customized family tree chart",
    "Knights and dragons coloring book",
    "Castle-shaped tea infuser",
    "Hand-carved wooden mead mug",
    "Wax sealing stamp set",
    "Dragon-shaped bookends",
    "Medieval-themed cookie stamps",
    "Renaissance fair season pass",
    "Illuminated manuscript coloring book",
    "Hand-forged iron bookmark",
    "Castle-shaped cake mold",
    "Medieval-themed phone case",
    "Dragon-themed chess piece set",
    "Historical battle strategy board game",
    "Leather-bound scroll holder",
    "Knight armor LEGO set",
    "Medieval-style garden gnome",
    "Historical siege weapon model kit",
    "Themed medieval puzzle box",
    "Dragon-shaped wine stopper",
    "Renaissance-style goblet charm",
    "Castle-shaped key holder",
    "Medieval-themed embroidery kit",
    "Hand-painted knight figurine",
    "Illuminated manuscript bookmark",
    "Medieval-style board game collection",
    "Antique-style parchment paper and quill set",
]

case_study_names = [
    "The Chronicles of Aelfric the Valiant",
    "The Saga of Lady Isabeau's Rebellion",
    "The Ballad of Roderick the Bold",
    "The Quest for the Scepter of Charlemagne",
    "The Epic of Giselle the Enchantress",
    "The Tale of Ealdred the Conqueror",
    "The Odyssey of Bernadette the Fearless",
    "The Legend of Thibault's Honor",
    "The Chronicle of Sir Reynard's Quest",
    "The Saga of Yvette and the Lost Kingdom",
    "The Journey of Marcelin the Mystic",
    "The Quest for the Ebon Crown of Orleans",
    "The Adventures of Elowen the Shieldmaiden",
    "The Tale of Aeliana and the Dragon's Hoard",
    "The Legend of Roland the Loyal",
    "The Saga of Claudette's Destiny",
    "The Ballad of Armand the Wanderer",
    "The Odyssey of Louisette's Redemption",
    "The Epic of Hugo the Unyielding",
    "The Chronicles of Vivienne the Valorous",
    "The Quest for the Lost Relic of Aquitaine",
    "The Legend of Odette the Swan Maiden",
    "The Tale of Adelard the Minstrel-Knight",
    "The Saga of Henri and the Ghostly Horde",
    "The Ballad of Gervaise the Wise",
    "The Odyssey of Orlane the Shieldmaiden",
    "The Chronicle of Leofric's Vengeance",
    "The Quest for the Sapphire Chalice",
    "The Epic of Aveline the Archer",
    "The Legend of Théodoric the Thunderstruck",
    "The Saga of Seraphine and the Moonlit Prophecy",
    "The Tale of Alaric the Runebearer",
    "The Adventures of Élodie the Druidess",
    "The Quest for the Golden Harp of Brittany",
    "The Chronicles of Baldwin the Benevolent",
    "The Ballad of Raimond the Righteous",
    "The Odyssey of Gisèle the Gallant",
    "The Epic of Céleste the Sorceress",
    "The Legend of Alaric the Last Paladin",
    "The Saga of Aveline's Destiny",
]

episode_names = [
    "Epistolary Gathering of the Franks",
    "Correspondence Banquet at Carolingian Court",
    "The Scriptorium Symposium",
    "Missive Exchange of Merovingian Scholars",
    "Parchment Palaver in Aquitaine",
    "Diplomatic Dispatch in Visigothic Toledo",
    "Royal Scroll Exchange of the Lombards",
    "Epistle Deliberations of Byzantine Envoys",
    "Lettered Conclave of the Celtic Tribes",
    "Courier Convocation in Hibernia",
    "Manuscript Maven Meet-up",
    "Scriptural Soiree of the Saxons",
    "Scroll Symposium in Gaul",
    "Epistolarian Assembly in Iberia",
    "Dispatch Dialogue of the Vandals",
    "Lettered Liaison in Ostrogothic Ravenna",
    "Penmanship Parley of the Suebi",
    "Corresponding Congress in Lombard Pavia",
    "Epistle Exchange of the Bretons",
    "Papal Papyrus Pondering",
    "Carolingian Courier Commune",
    "Merovingian Missive Mingle",
    "Aquitainian Amanuensis Affair",
    "Scriptorial Salon of Tours",
    "Chancery Conference in Austrasia",
    "Vellum Verbalization in Neustria",
    "Diplomatic Dispatches in Byzantium",
    "Epistolary Ensemble of the Alans",
    "Gallicus Grammaticus Gathering",
    "Manuscript Mediation of the Moors",
    "Saxon Scroll Symposium",
    "Parchment Pageant in Visigothic Hispania",
    "Correspondence Caucus of the Clovis Clan",
    "Palimpsest Parley of the Ostrogoths",
    "Scrollcraft Soiree in the Rhineland",
    "Vandalic Versification Venture",
    "Iberian Inkwell Intercourse",
    "Celtica Codex Conclave",
    "Missive Mingling of the Merovingians",
    "Epistolarian Embarkation in Eire",
    "Lombardic Letter Labyrinth",
    "Papyrus Pilgrimage of the Papal See",
    "Suebic Script Scrutiny",
    "Bretonic Billet Banquet",
    "Ravenna Rebus Rendezvous",
    "Ostrogothic Oration Outing",
    "Scripter's Salon in Gaul",
    "Vandalic Verse Vigil",
    "Iberian Inkpot Inquiry",
    "Celtic Codex Conference",
    "Tours Transcription Tryst",
    "Chancery Caucus in Austrasia",
    "Visigothic Vellum Venture",
    "Neustrian Notation Nuptials",
    "Byzantine Billet Banter",
    "Alans' Amanuensis Assembly",
    "Scriptorial Symposium of Saxons",
    "Moors' Manuscript Meet-up",
    "Rhineland Runic Recital",
    "Clovis Clan Correspondence",
    "Ostrogothic Ostraca Occasion",
    "Gallicus Grammaticus Gala",
    "Suebic Script Swap",
    "Lombardic Letter Lament",
    "Papal Papyrus Prelude",
    "Neustrian Notation Nomenclature",
    "Byzantine Billet Blitz",
    "Aquitainian Amanuensis Accord",
    "Saxon Scripter Soiree",
    "Clovis Clan Correspondence Carnival",
    "Manuscript Maven Mashup",
    "Iberian Inkpot Incantation",
    "Neustrian Notation Narratives",
    "Celtic Codex Compendium",
    "Lombardic Letter League",
    "Missive Maven Mingle",
    "Bretonic Billet Bacchanal",
    "Chancery Caucus Celebration",
    "Carolingian Courier Confluence",
    "Epistolary Ensemble Extravaganza",
    "Parchment Pageant Parade",
    "Scripter's Salon Soirée",
    "Diplomatic Dispatch Dalliance",
    "Papal Papyrus Pageantry",
    "Corresponding Congress Carnival",
    "Manuscript Mediation Merriment",
    "Epistolarian Embarkation Extravaganza",
    "Vellum Verbalization Voyage",
    "Papyrus Pilgrimage Pageant",
    "Iberian Inkwell Intercourse Incantation",
    "Carolingian Courier Commune Carnival",
    "Merovingian Missive Mingle Melody",
    "Aquitainian Amanuensis Affair Assemblage",
    "Scriptorial Salon of Tours Celebration",
    "Chancery Conference Commotion",
    "Vellum Verbalization Venture Variations",
    "Ravenna Rebus Rendezvous Revelry",
    "Scripter's Salon Soirée Spectacle",
    "Corresponding Congress Carnival Celebration",
    "Manuscript Mediation Merriment Marathon",
]


letter_category_names = [
    "Personal Letter",
    "Business Letter",
    "Love Letter",
    "Apology Letter",
    "Thank-You Letter",
    "Sympathy Letter",
    "Condolence Letter",
    "Recommendation Letter",
    "Cover Letter",
    "Job Acceptance Letter",
    "Resignation Letter",
    "Complaint Letter",
    "Request Letter",
    "Invitation Letter",
    "Congratulations Letter",
    "Welcome Letter",
    "Retirement Letter",
    "Anniversary Letter",
    "Holiday Greeting Letter",
    "Graduation Letter",
    "Farewell Letter",
    "Introduction Letter",
    "Sales Letter",
    "Acknowledgment Letter",
    "Follow-Up Letter",
    "Reference Letter",
    "Confirmation Letter",
    "Permission Letter",
    "Encouragement Letter",
    "Announcement Letter",
    "Sponsorship Letter",
    "Query Letter",
    "Fundraising Letter",
    "Informal Letter",
    "Formal Letter",
    "Circular Letter",
]

source_names = [
    "Liber Sanctus: Divine Chronicles of the Holy Order",
    "Codex Illuminatus: Sacred Scriptures of the Ancient Monastery",
    "Manuscriptum Ecclesiasticum: The Canonical Records",
    "Chronicon Monasticum: Annals of the Sacred Cloister",
    "Sacramentum Codicis: Rituals and Liturgy of the Pious Brotherhood",
    "Antiqua Legenda Monastica: Tales of the Venerable Saints",
    "Divinum Evangelium: The Gospel According to the Monastic Scribes",
    "Sacra Compendium: Compilation of Sacred Wisdom",
    "Regula Monastica: Rules and Observances of the Holy Abbey",
    "Dei Opus Magnum: The Great Work of Divine Service",
    "Graduale Sanctum: Gradual Psalms of the Devout Choristers",
    "Liber Mysticus: Mystic Writings of the Silent Order",
    "Codicis Celestis: Heavenly Code of Monastic Conduct",
    "Sermones Exordiales: Inaugural Sermons of the Monastic Elders",
    "Scriptura Aurea: Golden Script of the Ancient Monastery",
    "Mysterium Divinorum: Secrets of the Divine",
    "Peregrinatio Sacra: Sacred Pilgrimages and Journeys",
    "Codex Seraphicus: Angelic Codes of Celestial Harmony",
    "Sententiae Sacrae: Sacred Sayings of the Sages",
    "Symbolum Sanctum: Symbols of Holiness and Devotion",
    "Cantus Celestialis: Heavenly Chants of the Devout",
    "Monastica Doctrina: Monastic Teachings and Philosophies",
    "Codex Mirabilis: Miraculous Tales of the Monastic Order",
    "Chronica Divina: Divine Chronicles of Sacred History",
    "Ritus Sacramentorum: Sacramental Rites of the Holy Order",
    "Ordo Celestis: Celestial Order of the Monastic Realm",
    "Mysteria Fidei: Mysteries of Faith and Devotion",
    "Hymnorum Sacrorum: Sacred Hymns and Anthems",
    "Testamentum Sanctum: Holy Testament of the Ancients",
    "Cantica Angelica: Angelic Canticles and Hymns",
    "Leges Divinitatis: Laws of Divine Governance",
    "Vita Ascetica: Ascetic Life and Spiritual Disciplines",
    "Luminare Monasticum: Monastic Illuminations and Insights",
    "Custodes Sacri: Keepers of the Sacred Traditions",
    "Tabula Sanctitatis: Table of Sanctity and Virtue",
    "Praecepta Divina: Divine Precepts of the Monastic Order",
    "Ars Contemplativa: Art of Contemplation and Meditation",
    "Serenus Ordo: Serene Order of the Divine Realm",
    "Cathedra Divina: Divine Seat of Spiritual Authority",
    "Antiphonarium Sacrum: Sacred Antiphons and Responses",
    "Scriptorium Sacrosanctum: Sacred Scriptorium of Wisdom",
    "Pax Aeterna: Eternal Peace of the Monastic Heart",
    "Cantus Seraphicus: Seraphic Chants of the Heavenly Choir",
    "Disciplina Mystica: Mystical Discipline of the Devout",
    "Chronica Angelorum: Chronicles of the Angelic Host",
    "Sacra Vestigia: Sacred Footsteps of the Devout",
    "Tribunalia Divina: Divine Tribunals of the Holy Order",
    "Lumen Divinitatis: Light of Divinity in Monastic Life",
    "Corona Sacra: Sacred Crown of the Monastic Calling",
    "Archivum Celeste: Celestial Archives of the Sacred Order",
    "Lex Imperialis: Imperial Laws and Edicts",
    "Conventus Regalis: Proceedings of the Royal Assembly",
    "Codex Politico: Political Codes and Decrees",
    "Annalia Regnorum: Annals of the Kingdoms",
    "Res Gestae Nobilium: Deeds of the Nobility",
    "Diplomatum Magnum: Great Diplomatic Treaties",
    "Chronica Potentatum: Chronicles of the Mighty Powers",
    "Mandata Praetoria: Prætorian Mandates and Orders",
    "Ordo Civitatum: Order of the City-States",
    "Comitia Magna: Grand Council Proceedings",
    "Imperium Sacrum: Sacred Empire and its Governance",
    "Civitatum Foedus: Pact of the Allied Cities",
    "Leges Concordiae: Laws of Concord and Unity",
    "Rerum Politicarum: Political Affairs and Events",
    "Rescripta Imperatorum: Imperial Rescripts and Decrees",
    "Charta Libertatis: Charter of Liberties",
    "Consilia Magistrorum: Councils of the Wise",
    "Foedus Militare: Military Alliances and Treaties",
    "Regnum Aeternum: Eternal Kingdom and its Laws",
    "Constitutio Civitatis: Constitution of the City",
    "Bellorum Decretum: Decrees of War and Peace",
    "Pacta Gentium: Pacts Among the Nations",
    "Vox Populi: Voice of the People in Governance",
    "Concilium Regale: Royal Council and its Proceedings",
    "Magistri Politico: Masters of Political Philosophy",
    "De Republica: On the State and its Structures",
    "Mandatum Senatus: Senate Mandates and Resolutions",
    "Regalis Machinatio: Royal Machinations and Intrigues",
    "Respublica Incepta: The Commencement of the Republic",
    "Magistri Diplomatici: Masters of Diplomacy and ,Statecraft"
    "Foederatio Gentium: League of the Nations",
    "Leges Urbis: Laws of the City",
    "Praetorium Decretum: Prætorial Decrees and Judgments",
    "Imperium Justitiae: Empire of Justice and Equity",
    "Tabula Foederum: Table of Alliances and Treaties",
    "Decretum Nobilium: Decrees of the Nobility",
    "Regalis Scepter: The Royal Scepter and its Authority",
    "Pactum Regium: Royal Pact and Agreements",
    "Politicae Machinae: Machinations of Political Strategy",
    "Juramentum Civium: Oaths of the Citizens",
    "Foedus Regnorum: Alliance of the Realms",
    "Vox Regalis: Royal Voice and Pronouncements",
    "Magistri Politici: Masters of Political Science",
    "Exordium Regni: The Beginning of the Kingdom",
    "Civitas Orbis: City-State of the World",
    "Regium Concilium: Royal Council of Governance",
    "Foederis Custodes: Guardians of the Alliance",
    "Vox Nobilitatis: Voice of the Nobility in Council",
    "Concordia Regum: Harmony Among the Kings",
    "Imperium Justorum: Empire of the Just Rulers",
]

group_names = [
    "Nobility of Camelot",
    "Clergy of Byzantium",
    "Peasantry of Aquitaine",
    "Serfs of Saxony",
    "Artisans of Florence",
    "Merchants of Cordoba",
    "Warriors of Gaul",
    "Slaves of Carthage",
    "Scholars of Alexandria",
    "Bureaucrats of Rome",
    "Monarchs of Iberia",
    "Landowners of Etruria",
    "Freeholders of Lombardy",
    "Tribespeople of Britannia",
    "Guildsmen of York",
    "Laborers of Sussex",
    "Herders of Caledonia",
    "Fishermen of Thessaloniki",
    "Traders of Constantinople",
    "Scribes of Papyrus",
    "Soldiers of Ravenna",
    "Aristocracy of Alemannia",
    "Vassals of Valencia",
    "Priests of Gaul",
    "Monks of Ravenna",
    "Farmers of Hispania",
    "Hunters of Transylvania",
    "Nomads of Pannonia",
    "Townsfolk of Lutetia",
    "Craftsmen of Tuscany",
    "Miners of Cornwall",
    "Artisans of Damascus",
    "Servants of Napoli",
    "Squires of Brittany",
    "Courtiers of Paris",
    "Scholars of Baghdad",
    "Alchemists of Granada",
    "Astrologers of Samarkand",
    "Peasant Revolters of Normandy",
    "Chieftains of Ireland",
    "Royal Guards of Antioch",
    "Shamans of Scandinavia",
    "Diplomats of Arles",
    "Entertainers of Athens",
    "Bandits of Sardinia",
    "Hermits of Sinai",
    "Crusaders of Jerusalem",
    "Knights of Valencia",
    "Pages of Pamplona",
    "Maids of Milan",
]
