# Generated by Django 4.2.7 on 2024-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('case_studies', models.ManyToManyField(related_name='episodes', to='case_study.casestudy')),
            ],
        ),
    ]
