# Generated by Django 4.2.7 on 2024-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_initial'),
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description to help identify this object'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='name',
            field=models.CharField(help_text='A name to help identify this object', max_length=200),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to help identify this object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer description to help identify this object')),
                ('events', models.ManyToManyField(blank=True, help_text='Events that make up this episode', to='event.eventdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='episodes',
            field=models.ManyToManyField(blank=True, help_text='Episodes involved in this case study', to='case_study.episode'),
        ),
    ]
