# Generated by Django 4.2.7 on 2024-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_alter_eventcategory_options_episode"),
        ("case_study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="description",
            field=models.TextField(
                blank=True, help_text="Longer description to help identify this object"
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="name",
            field=models.CharField(
                help_text="A name to help identify this object", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="episodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Episodes involved in this case study",
                to="event.episode",
            ),
        ),
    ]
