# Generated by Django 4.2.7 on 2024-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventdescription_source_and_more'),
        ('case_study', '0002_casestudy_description_alter_casestudy_name_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='event_descriptions',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='event.eventdescription'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='case_studies',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='case_study.casestudy'),
        ),
    ]
