# Generated by Django 4.2.7 on 2024-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_alter_persondateofbirth_person_and_more'),
        ('space', '0008_alter_spacedescription_source'),
        ('case_study', '0002_casestudy_description_alter_casestudy_name_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='key_persons',
            field=models.ManyToManyField(blank=True, help_text='Key historical figures involved in this case study', to='person.historicalperson'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='key_sites',
            field=models.ManyToManyField(blank=True, help_text='Key historical sites involved in this case study', to='space.structure'),
        ),
    ]
