# Generated by Django 4.2.7 on 2024-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_remove_eventdescriptionagent_source_terminology_and_more"),
        ("case_study", "0003_casestudy_key_persons_casestudy_key_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="episodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Series involved in this case study",
                to="event.episode",
            ),
        ),
    ]
