# Generated by Django 4.2.7 on 2025-06-23 14:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0030_alter_episode_contributors'),
        ('source', '0007_source_is_public'),
        ('case_study', '0005_rename_episodes_casestudy_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='series',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='content',
            field=models.TextField(blank=True, help_text='Article content (in HTML)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Author(s) of the case study', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.date(2025, 6, 23), help_text='Date of writing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudy',
            name='episodes',
            field=models.ManyToManyField(blank=True, help_text='Epistolary episodes that are the focus of the case study', to='event.episode'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Source texts that are the focus of the case study', to='source.source'),
        ),
    ]
