# Generated by Django 4.2.7 on 2025-11-06 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_remove_source_edition_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_study', '0006_remove_casestudy_series_casestudy_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='key_persons',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='key_sites',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Author(s) of the case study', related_name='case_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Source texts that are the focus of the case study', related_name='case_studies', to='source.source'),
        ),
    ]
