# Generated by Django 4.2.7 on 2025-10-20 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_study', '0006_remove_casestudy_series_casestudy_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Author(s) of the case study', related_name='case_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
