# Generated by Django 4.2.26 on 2025-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0007_remove_casestudy_episodes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-date'], 'verbose_name': 'case study', 'verbose_name_plural': 'case studies'},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date',
            field=models.DateField(help_text='Date of writing'),
        ),
    ]
